baseURL = 'https://wolkenschloesserundco.de/'

theme = 'LoveIt'
title = "Grünzschocher"

defaultContentLanguage = 'de'
languageCode = 'de-De'
languageName = "German"

# Summary length for posts (in words)
summaryLength = 180

enableEmoji = true

[params]
defaultTheme = 'light'
title = "Grünzschocher"
description = "Grünzschocher ist ein Wohnprojekt am Entstehen. Das Kunstwort Grünzschocher beschreibt den Ort - irgendwie Großzschocher, aber gleichzeitig Grünzschocher"

[params.home.posts]
enable = false

[params.header.title]
#name = "Grünzschocher"
name = ""
logo = ""
pre = ""
post = ""

[params.home.profile]
subtitle = "Ein Wohnprojekt in Gründung"
title = "Willkommen in Grünzschocher"

[params.footer]
enable = true
author = false
copyright = false
since = 2025
# Simple markdown relative references do not point to correct page - baseURL missing PR-number in staging environment
custom = "[Impressum](/impressum) | [Datenschutzerklärung](/datenschutz)"


[params.section]
paginate = 6


# Menu config
  [[menu.main]]
    weight = 1
    identifier = "posts"
    # you can add extra information before the name (HTML format is supported), such as icons
    pre = ""
    # you can add extra information after the name (HTML format is supported), such as icons
    post = ""
    name = "Aktuelles"
    url = "/posts/"
    # title will be shown when you hover on this menu link
    title = ""
  [[menu.main]]
    weight = 2
    identifier = "unterstuetzen"
    # you can add extra information before the name (HTML format is supported), such as icons
    pre = ""
    # you can add extra information after the name (HTML format is supported), such as icons
    post = ""
    name = "Unterstützen"
    url = "/unterstuetzen/"
    # title will be shown when you hover on this menu link
    title = "Wir suchen Unterstützung bei der Finanzierung"


# Author config
[author]
  name = "Die BewohnerInnen"

# Options to make hugo output files
[outputs]
  home = ["HTML", "JSON"]

[params.page.code.render]
      goat = false
      mermaid = false

[params.page.share]
      enable = false

[page.social]
Instagram = false

# Markup related configuration in Hugo
[markup]
  # Syntax Highlighting (https://gohugo.io/content-management/syntax-highlighting)
  [markup.highlight]
    # false is a necessary configuration (https://github.com/dillonzq/LoveIt/issues/158)
    noClasses = false
    #style = 'monokai'
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
      headingAnchor = false
